CREATE OR REPLACE TEMPORARY TABLE AUTH_NOTIFICATION_TYPES AS
SELECT DISTINCT
    TRIM(r."authorizationid")   AS AUTHORIZATIONID,
    CASE
        WHEN UPPER(TRIM(COALESCE(q."description", ''))) LIKE '%MODIFIED%' THEN 'MODIFIED'
        WHEN UPPER(TRIM(COALESCE(q."description", ''))) LIKE '%EXTEN%LETTER%' THEN 'EXTENSION'
        WHEN UPPER(TRIM(COALESCE(q."description", ''))) LIKE '%EXTEN%ORAL%' THEN 'EXTENSION ORAL'
        WHEN UPPER(TRIM(COALESCE(q."description", ''))) LIKE '%EXTEN%THRESH%' THEN 'EXTENSION THRESHOLD'
        WHEN UPPER(TRIM(COALESCE(q."description", ''))) LIKE '%AUTH%NOTIFI%LETT%SENT%' THEN 'NOTIFICATION'
        WHEN UPPER(TRIM(COALESCE(q."description", ''))) LIKE '%THRESH%SENT%' THEN 'THRESHOLD'
        WHEN UPPER(TRIM(COALESCE(q."description", ''))) LIKE '%ORAL%NOTIFI%PROVID%' THEN 'ORAL'
        ELSE q."description"
    END AS NOTIFICATION_TYPE
FROM PROD_CHG_ODS.HMOPROD_PLANDATA.QATTRIBUTE AS q
JOIN PROD_CHG_ODS.HMOPROD_PLANDATA.REFERRALATTRIBUTE AS attrib ON q."attributeid" = attrib."attributeid"
JOIN PROD_CHG_ODS.HMOPROD_PLANDATA.REFERRAL AS r ON attrib."referralid" = r."referralid"
WHERE UPPER(TRIM(COALESCE(q."description", ''))) LIKE '%MODIFIED%'
   OR UPPER(TRIM(COALESCE(q."description", ''))) LIKE '%EXTEN%'
   OR UPPER(TRIM(COALESCE(q."description", ''))) LIKE '%AUTH%NOTIFI%LETT%SENT%'
   OR UPPER(TRIM(COALESCE(q."description", ''))) LIKE '%THRESH%SENT%'
   OR UPPER(TRIM(COALESCE(q."description", ''))) LIKE '%ORAL%NOTIFI%PROVID%'
   OR UPPER(TRIM(COALESCE(q."description", ''))) LIKE '%UNABLE%SEND%';

-- Step 2: All approved SNF auths for Country Hills & Stillwater
SELECT DISTINCT
    fmh.AUTHORIZATION_ID,
    fmh.AUTHORIZATION_STATUS,
    fmh.MEMBERAK                                              AS MEMBER_ID,
    das.AUTHORIZATION_TEMPLATE,
    claimak
    
    das.HCPC_CODE_1,
    das.HCPC_DESCRIPTION_1,
    refer_from.PROVIDER_FULL_NAME                             AS REQUESTING_PROVIDER,
    facility.PROVIDER_FULL_NAME                               AS SNF_FACILITY,
    TO_DATE(fmh.ADMIT_DATE::VARCHAR, 'YYYYMMDD')              AS ADMIT_DATE,
    TO_DATE(fmh.DISCHARGE_DATE::VARCHAR, 'YYYYMMDD')          AS DISCHARGE_DATE,
    TO_DATE(fmh.AUTHORIZATION_EFFECTIVE_DATE::VARCHAR, 'YYYYMMDD') AS AUTHORIZATION_EFFECTIVE_DATE,
    TO_DATE(fmh.AUTHORIZATION_TERMINATION_DATE::VARCHAR, 'YYYYMMDD') AS AUTHORIZATION_TERMINATION_DATE,
    fmh.AUTH_UNITS                                            AS AUTHORIZED_UNITS,
    fmh.REFERRAL_SERVICE_CODE,
    COALESCE(nt.NOTIFICATION_TYPE, 'NONE')                    AS AUTH_NOTIFICATION_TYPE
FROM PROD_CHG_EDW.CHG_EDW.FACT_MEMBERHISTORY AS fmh
JOIN PROD_CHG_EDW.CHG_EDW.DIM_AUTHORIZATIONSERVICE AS das ON fmh.AUTHORIZATIONSERVICESK = das.AUTHORIZATIONSERVICESK
JOIN PROD_CHG_EDW.CHG_EDW.DIM_PROVIDERSPECIALTY AS rend ON fmh.providersk = rend.PROVIDERSK
JOIN PROD_CHG_EDW.CHG_EDW.DIM_PROVIDERSPECIALTY As payto ON fmh.paytoprovidersk = payto.PROVIDERSK
JOIN PROD_CHG_EDW.CHG_EDW.DIM_PROVIDERSPECIALTY AS facility ON fmh.AUTHORIZATIONTOPROVIDERSK = facility.PROVIDERSK
LEFT JOIN PROD_CHG_EDW.CHG_EDW.DIM_PROVIDERSPECIALTY AS refer_from ON fmh.AUTHORIZATIONFROMPROVIDERSK = refer_from.PROVIDERSK
LEFT JOIN AUTH_NOTIFICATION_TYPES AS nt ON fmh.AUTHORIZATION_ID = nt.AUTHORIZATIONID
WHERE fmh.IS_SNF = 'YES'
  AND UPPER(fmh.AUTHORIZATION_STATUS) = 'APPROVED'
  AND (facility.PROVIDERAK IN ('780', '336158', '361570') 
            OR
       rend.PROVIDERAK IN ('780', '336158', '361570') 
            OR-- COUNTRY HILLS HEALTH CARE, COUNTRY HILLS POST ACUTE, STILLWATER POST-ACUTE
       payto.PROVIDERAK IN ('780', '336158', '361570'))
  AND refer_from.PROVIDERAK IN ('780', '336158', '361570')
ORDER BY TO_DATE(fmh.AUTHORIZATION_EFFECTIVE_DATE::VARCHAR, 'YYYYMMDD');
